# Generated by Django 5.1.3 on 2025-01-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_webpage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='lahari@gmail.com', max_length=254),
        ),
    ]
